version: '3.8'

services:
  invoice-service:
    image: invoice/invoice-service:0.0.1-SNAPSHOT
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"